version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    container_name: orion-api
    networks:
      - backend-network
networks:
    backend-network:
        driver: bridge
