version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:80"
    container_name: orion
    networks:
      - backend-network
networks:
    backend-network:
        driver: bridge
