name: Container publish

on:
  push:
    branches: [ master ]
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    
  push_to_registry:
    needs: [build]
    name: DockerHub Publish
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vanderlangs/orion-api
          tag_with_ref: true
